### ISSUE TITLE
User can post a new simple ticket

### ISSUE THREAD

**Issue by surrealist** [surrealist/contactus#2]
The very simple version of Ticket consists of:
- Title
- Content body

The system should generate other fields automatically:
- Ticket Id*
- Created Date

**Comment by surrealist** [comment]
**Ticket Id**
- automatically generated when create a new Ticket
- is a string of hexadecimal (0-9, a-f).
- uses lowercase
- length is 6 characters
- not duplicate to existing tickets

**Comment by sstae** [comment]
**Ticket Id**
- automatically generated when create a new ticket
- is a string of Hexadecimal (0=9,a-f)
- use lowercase
- length 6 characters
- not duplicate to existing tickets
